name: locarb_attendance
description: LoCarb Attendance
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # نسخ متوافقة سحابيًا (CI) مع Flutter 3.22
  firebase_core: 2.31.1
  firebase_auth: 4.19.6
  cloud_firestore: 4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:
  uses-material-design: true
