name: your_project_name
description: A new Flutter project for HR attendance with admin panel
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (متوافقة مع بعض)
  firebase_core: ^2.28.0
  firebase_auth: 4.16.0
  cloud_firestore: 4.15.0
  

  # State / UI
provider: 6.1.2

  # Export
  excel: 2.1.0         # ← مثبت (يدعم setColWidth و CellStyle.backgroundColorHex)
  csv: 5.1.1
  share_plus: 10.0.0   # ← متوافق مع إصدارات firebase أعلاه

  # Utils
  intl: 0.19.0
  http: 1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true
