name: locarb_attendance
description: LoCarb Attendance
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"   # Flutter 3.22 = Dart 3.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.32.0
  firebase_auth: 4.19.6
  cloud_firestore: 4.17.5
  excel: ^2.1.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

# Important for resolving web conflicts with firebase_web
dependency_overrides:
  js: 0.6.7

flutter:
  uses-material-design: true
