name: locarb_attendance_fresh
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (زي ما هي من نسختك المستقرة)
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.15.0

  # UI / State (لو عندك)
  provider: ^6.1.2

  # Utilities
  intl: ^0.19.0
  http: ^1.2.2

  # Export (جديد)
  excel: 2.1.0

  flutter:
  uses-material-design: true

