name: your_project_name
description: A new Flutter project for HR attendance with admin panel
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core & auth
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0

  # UI & State management
  provider: ^6.1.2

  # Exporting packages
  csv: ^5.1.1
  excel: ^4.0.2
  share_plus: ^10.0.0

  # Utils
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
