name: locarb_attendance
description: A Flutter web app for LoCarb employee attendance and management.
publish_to: 'none' # This prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.7
  firebase_messaging: ^14.6.7

  # UI packages
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  google_fonts: ^4.0.4
  intl: ^0.18.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
